version:             '2'

services:
  db:
    image:               mysql:5.7
    restart:             always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE:      webapp
      MYSQL_USER:          webuser
      MYSQL_PASSWORD:      password
    ports:
      - "3307:3306"
  web:
    image: rs:v3
    build: .
    environment:
      RAILS_ENV: production
    ports:
      - "80:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: webapp
      DB_PASSWORD: password
      DB_HOST: db
