apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: db
        - name: DB_NAME
          value: webapp
        - name: DB_PASSWORD
          value: password
        - name: DB_USER
          value: webuser
        image: gcr.io/basicproject-196205/rs:updates
        name: web
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      volumes:
      - name: web-claim0
        persistentVolumeClaim:
          claimName: web-claim0
status: {}
